<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class Tbl_kode_kata_seeder extends Seeder
{
    public function run()
    {

        $tbl_name = 'tbl_kode_kata';

        $data = [
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'jenis_kelamin',
                'tampilan_kata'      => 'laki-laki',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'jenis_kelamin',
                'tampilan_kata'      => 'perempuan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'tipe_user',
                'tampilan_kata'      => 'master',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'tipe_user',
                'tampilan_kata'      => 'operator',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'tipe_user',
                'tampilan_kata'      => 'penduduk',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'email_verified',
                'tampilan_kata'      => 'email belum di verifikasi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'email_verified',
                'tampilan_kata'      => 'email sudah di verifikasi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'status_user',
                'tampilan_kata'      => 'dilarang',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'status_user',
                'tampilan_kata'      => 'diizinkan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Islam',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Protestan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Katolik',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Hindu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Buddha',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '6',
                'grup_kata'          => 'agama',
                'tampilan_kata'      => 'Khonghucu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Belum/Tidak Bekerja',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Mengurus Rumah Tangga',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pelajar/Mahasiswa',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pensiunan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pegawai Negeri Sipis (PNS)',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '6',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tentara Nasional Indonesia (TNI)',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '7',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Kepolisian RI (POLRI)',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '8',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Perdagangan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '9',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Petani/Perkembun',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '10',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Peternak',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '11',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Nelayan/Perikanan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '12',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Industri',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '13',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Konstruksi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '14',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Transportasi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '15',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Karyawan Swasta',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '16',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Karyawan BUMN',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '17',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Karyawan BUMD',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '18',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Karyawan Honorer',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '19',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Buruh Lepas Harian',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '20',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Burun Tani/Perkebunan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '21',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Burun Nelayan/Perikanan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '22',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Buruh Peternakan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '23',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pembantu Rumah tangga',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '24',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Cukur',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '25',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Listrik',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '26',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Batu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '27',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Kayu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '28',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Sol Sepatu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '29',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Las/Pandai Besi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '30',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Jahit',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '31',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tukang Gigi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '32',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penata Rias',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '33',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penata Busana',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '34',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penata Rambut',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '35',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Mekanik',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '36',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Seniman',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '37',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Tabib',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '38',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Paraji',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '39',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Perancang Busana',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '40',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penterjemah',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '41',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Imam Masjid',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '42',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pendeta',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '43',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pastor',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '44',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wartawan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '45',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Ustadz/Mubaligh',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '46',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Juru Masak',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '47',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Promotor Acara',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '48',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota DPR RI',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '49',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota DPD',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '50',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota BPK',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '51',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Presiden',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '52',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wakil Presiden',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '53',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota Mahkamah Konstitusi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '54',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota Kabinet/Kementrian',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '55',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Duta Besar',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '56',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Gubernur',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '57',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wakil Gubernur',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '58',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Bupati',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '59',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wakil Bupati',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '60',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Walikota',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '61',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wakil Walikota',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '62',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota DPRD Prop',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '63',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Anggota DPRD Kab./Kota',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '64',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Dosen',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '65',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Guru',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '66',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pilot',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '67',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pengacara',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '68',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Notaris',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '69',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Arsitek',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '70',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Akuntan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '71',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Konsultan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '72',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Dokter',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '73',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Bidan',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '74',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Perawat',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '75',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Apoteker',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '76',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Psikiater/Psikolog',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '77',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penyiar Televisi',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '78',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Penyiar Radio',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '79',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pelaut',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '80',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Peneliti',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '81',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Sopir',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '82',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pialang',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '83',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Paranormal',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '84',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Pedagang',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '85',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Perangkat Desa',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '86',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Kepala Desa',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '87',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Biarawati',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '88',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Wiraswasta',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '89',
                'grup_kata'          => 'jenis_pekerjaan',
                'tampilan_kata'      => 'Lainnya',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'status_perkawinan',
                'tampilan_kata'      => 'Belum Kawin',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'status_perkawinan',
                'tampilan_kata'      => 'Kawin',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'status_perkawinan',
                'tampilan_kata'      => 'Cerai Hidup',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'status_perkawinan',
                'tampilan_kata'      => 'Cerai Mati',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'A',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'AB',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'B',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'O',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'A+',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '6',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'B+',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '7',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'AB+',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '8',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'O+',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '9',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'A-',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '10',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'B-',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '11',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'AB-',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '12',
                'grup_kata'          => 'gol_darah',
                'tampilan_kata'      => 'O-',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Kepala Keluarga',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Suami',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Istri',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Anak',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Menantu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '6',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Cucu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '7',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Orang Tua',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '8',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Mertua',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '9',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Famili Lain',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '10',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Pembantu',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '11',
                'grup_kata'          => 'status_hubungan_dalam_keluarga',
                'tampilan_kata'      => 'Lainnya',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'SD',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'SMP',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'SMA',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Diploma 1',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Diploma 2',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '6',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Diploma 3',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '7',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Diploma 4',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '8',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Sarjana',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '9',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Magister',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '10',
                'grup_kata'          => 'pendidikan_terakhir',
                'tampilan_kata'      => 'Profesor/Doktor',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'jenis_tiket',
                'tampilan_kata'      => 'Surat Kelahiran',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'tempat_dilahirkan',
                'tampilan_kata'      => 'Rumah Sakit/Rumah Bersalin',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'tempat_dilahirkan',
                'tampilan_kata'      => 'Puskesmas',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'tempat_dilahirkan',
                'tampilan_kata'      => 'Polindes',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'tempat_dilahirkan',
                'tampilan_kata'      => 'Rumah',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '5',
                'grup_kata'          => 'tempat_dilahirkan',
                'tampilan_kata'      => 'Lainnya',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'jenis_kelahiran',
                'tampilan_kata'      => 'Tunggal',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'jenis_kelahiran',
                'tampilan_kata'      => 'Kembar 2',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'jenis_kelahiran',
                'tampilan_kata'      => 'Kembar 3',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'jenis_kelahiran',
                'tampilan_kata'      => 'Kembar 4',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '1',
                'grup_kata'          => 'penolong_kelahiran',
                'tampilan_kata'      => 'Dokter',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '2',
                'grup_kata'          => 'penolong_kelahiran',
                'tampilan_kata'      => 'Bidan/Perawat',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '3',
                'grup_kata'          => 'penolong_kelahiran',
                'tampilan_kata'      => 'Dukun',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ],
            [
                'nomor_kode'         => '4',
                'grup_kata'          => 'penolong_kelahiran',
                'tampilan_kata'      => 'Lainnya',
                'create_time'        => Time::now(),
                'update_time'        => Time::now(),
            ]
        ];

        $builder = $this->db->table($tbl_name);
        if (count($data) == 1) {
            $builder->insert($data[0]);
        } else if (count($data) > 100) {
            $builder->insertBatch($data);
        } else {
            foreach ($data as $value) {
                $builder->insert($value);
            }
        }
    }
}
